<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="LiteDB" Version="5.0.21" />
    <PackageVersion Include="Microsoft.Data.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.203" />
    <PackageVersion Include="Novolis.Storage.LiteDb" Version="2026.1.*" />
    <PackageVersion Include="Novolis.Storage.Sqlite" Version="2026.1.*" />
    <PackageVersion Include="Spectre.Console" Version="0.54.0" />
    <PackageVersion Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.5" />
    <PackageVersion Include="System.CommandLine" Version="2.0.10" />
    <PackageVersion Include="TUnit" Version="1.44.39" />
  </ItemGroup>
</Project>
