using System.Text;

namespace Novolis.Tools.Docs.Org;

/// <summary>Renders an <see cref="OrgStatusSnapshot"/> into the org profile README block.</summary>
public static class OrgStatusMarkdown
{
    /// <summary>Builds the marked status block, including the markers.</summary>
    public static string Build(OrgStatusSnapshot snapshot)
    {
        var org = snapshot.Org;
        var docs = $"https://{org.ToLowerInvariant()}.github.io/.github/";
        var sb = new StringBuilder();
        sb.AppendLine(OrgLandingStatusUpdater.StartMarker);
        sb.AppendLine();
        sb.AppendLine($"<!-- Generated by novolis-docs org-readme — do not hand-edit. Last run: {snapshot.GeneratedAt} -->");
        sb.AppendLine();
        sb.AppendLine(
            $"{Labeled("failure", "Failed")} **{snapshot.FailedCount}** · " +
            $"{Labeled("release", "Shipped")} **{snapshot.ReleasedRepoCount}** · " +
            $"{Labeled("package", "Packages")} **{snapshot.PackageCount}** · " +
            $"{Labeled("merge", "Merges")} **{snapshot.MergeSuccesses}** / {snapshot.RepoCount} " +
            $"· {snapshot.GeneratedAt} · [docs]({docs})");
        sb.AppendLine();
        AppendFailures(sb, org, snapshot);
        AppendReleases(sb, org, snapshot);
        AppendInventory(sb, org, snapshot);
        sb.AppendLine(OrgLandingStatusUpdater.EndMarker);
        return sb.ToString();
    }

    private static void AppendFailures(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine($"### {Labeled("failure", "Failed")}");
        sb.AppendLine();
        if (snapshot.Failures.Count == 0)
        {
            sb.AppendLine("No failed or cancelled merge or release runs in the latest completed workflow for each repository.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| When | Repository | Workflow | Result | Error |");
        sb.AppendLine("|------|------------|----------|--------|-------|");
        foreach (var row in snapshot.Failures)
        {
            sb.Append("| ").Append(Cell(row.When));
            sb.Append(" | ").Append(RepoLink(org, row.Repo));
            sb.Append(" | ").Append(WorkflowName(row.Workflow));
            sb.Append(" | ").Append(ConclusionMark(row.Conclusion, row.Url));
            sb.Append(" | ").Append(Cell(string.IsNullOrWhiteSpace(row.Error) ? row.Title : row.Error));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
    }

    private static void AppendReleases(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine($"### {Labeled("release", "Shipped")}");
        sb.AppendLine();
        if (snapshot.Releases.Count == 0)
        {
            sb.AppendLine("No GitHub Releases published.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Published | Repository | Tag | Channel |");
        sb.AppendLine("|-----------|------------|-----|---------|");
        foreach (var row in snapshot.Releases)
        {
            sb.Append("| ").Append(Cell(row.Published));
            sb.Append(" | ").Append(RepoLink(org, row.Repo));
            sb.Append(" | ").Append(Linked($"`{row.Tag}`", row.Url));
            sb.Append(" | ").Append(ChannelMark(row.Channel));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
    }

    private static void AppendInventory(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine("<details>");
        sb.AppendLine($"<summary>{Labeled("package", "What we have")} — {snapshot.RepoCount} repositories, {snapshot.PackageCount} packages</summary>");
        sb.AppendLine();
        sb.AppendLine("| Repository | Packages | GitHub Packages | nuget.org | Last release | Merge | Release |");
        sb.AppendLine("|------------|----------|-----------------|-----------|--------------|-------|---------|");
        foreach (var row in snapshot.Repos)
        {
            var packagesUrl = row.PackageCount > 0
                ? $"[{row.PackageCount}](https://github.com/orgs/{org}/packages?repo_name={row.Name})"
                : "0";
            var release = string.IsNullOrWhiteSpace(row.ReleaseTag)
                ? "—"
                : Linked($"`{row.ReleaseTag}`", row.ReleaseUrl);
            sb.Append("| ").Append(RepoLink(org, row.Name));
            sb.Append(" | ").Append(packagesUrl);
            sb.Append(" | ").Append(Mono(row.GprVersion));
            sb.Append(" | ").Append(Mono(row.NugetVersion));
            sb.Append(" | ").Append(release);
            sb.Append(" | ").Append(ConclusionMark(row.MergeConclusion, row.MergeUrl));
            sb.Append(" | ").Append(ConclusionMark(row.ReleaseConclusion, row.ReleaseRunUrl));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
        sb.AppendLine("</details>");
        sb.AppendLine();
    }

    private static string Mark(string file, string alt) =>
        $"<img src=\"https://raw.githubusercontent.com/Novolis-Platform/.github/main/brand/status/{file}.svg\" width=\"16\" height=\"16\" alt=\"{alt}\">";

    private static string Labeled(string file, string label) =>
        $"{Mark(file, label)} {label}";

    private static string WorkflowName(string workflow) =>
        workflow.Contains("release", StringComparison.OrdinalIgnoreCase) ? "release" : "merge";

    private static string ConclusionMark(string conclusion, string url)
    {
        var (file, word) = conclusion switch
        {
            "success" => ("success", "passed"),
            "cancelled" => ("cancelled", "cancelled"),
            "failure" => ("failure", "failed"),
            _ => ("", ""),
        };
        if (file.Length == 0)
        {
            return "—";
        }

        var label = Labeled(file, word);
        return string.IsNullOrWhiteSpace(url) ? label : $"<a href=\"{url}\">{label}</a>";
    }

    private static string ChannelMark(string channel)
    {
        if (channel.StartsWith("nuget.org ", StringComparison.Ordinal))
        {
            return Labeled("nuget", "nuget.org") + " `" + Cell(channel["nuget.org ".Length..]) + "`";
        }

        if (channel.EndsWith("release asset", StringComparison.Ordinal) ||
            channel.EndsWith("release assets", StringComparison.Ordinal))
        {
            return Labeled("release", Cell(channel.Split(' ')[0]) + " assets");
        }

        if (channel == "GitHub Release")
        {
            return Labeled("release", "GitHub Release");
        }

        return Cell(channel);
    }

    private static string RepoLink(string org, string repo) =>
        $"[`{repo}`](https://github.com/{org}/{repo})";

    private static string Linked(string label, string url) =>
        string.IsNullOrWhiteSpace(url) ? Cell(label) : $"[{label}]({url})";

    private static string Mono(string version) =>
        string.IsNullOrWhiteSpace(version) ? "—" : $"`{Cell(version)}`";

    private static string Cell(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return "—";
        }

        return text.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }
}
