using System.Text;

namespace Novolis.Tools.Docs.Org;

/// <summary>Renders an <see cref="OrgStatusSnapshot"/> into the org profile README block.</summary>
public static class OrgStatusMarkdown
{
    /// <summary>Builds the marked status block, including the markers.</summary>
    public static string Build(OrgStatusSnapshot snapshot)
    {
        var org = snapshot.Org;
        var docs = $"https://{org.ToLowerInvariant()}.github.io/.github/";
        var sb = new StringBuilder();
        sb.AppendLine(OrgLandingStatusUpdater.StartMarker);
        sb.AppendLine();
        sb.AppendLine($"<!-- Generated by novolis-docs org-readme — do not hand-edit. Last run: {snapshot.GeneratedAt} -->");
        sb.AppendLine();
        sb.AppendLine(
            $"Snapshot **{snapshot.GeneratedAt}**. Merge successes **{snapshot.MergeSuccesses}** / {snapshot.RepoCount}. " +
            $"Failed merge or release runs **{snapshot.FailedCount}**. " +
            $"Repositories with a GitHub Release **{snapshot.ReleasedRepoCount}**. " +
            $"NuGet packages on GPR **{snapshot.PackageCount}**. " +
            $"Same tables on the [portfolio docs]({docs}).");
        sb.AppendLine();
        AppendFailures(sb, org, snapshot);
        AppendReleases(sb, org, snapshot);
        AppendInventory(sb, org, snapshot);
        sb.AppendLine(OrgLandingStatusUpdater.EndMarker);
        return sb.ToString();
    }

    private static void AppendFailures(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine("### Releases and merges that failed");
        sb.AppendLine();
        sb.AppendLine("Latest completed `merge.yml` or `release.yml` run when that run failed or was cancelled.");
        sb.AppendLine();
        if (snapshot.Failures.Count == 0)
        {
            sb.AppendLine("No failed or cancelled merge or release runs in the latest completed workflow for each repository.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| When | Repository | Workflow | Run | Error |");
        sb.AppendLine("|------|------------|----------|-----|-------|");
        foreach (var row in snapshot.Failures)
        {
            sb.Append("| ").Append(Cell(row.When));
            sb.Append(" | ").Append(RepoLink(org, row.Repo));
            sb.Append(" | `").Append(Cell(row.Workflow)).Append('`');
            sb.Append(" | ").Append(Linked(row.Conclusion, row.Url));
            sb.Append(" | ").Append(Cell(string.IsNullOrWhiteSpace(row.Error) ? row.Title : row.Error));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
    }

    private static void AppendReleases(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine("### Releases that shipped");
        sb.AppendLine();
        sb.AppendLine("Latest GitHub Release per repository. GPR build numbers on `main` are continuous packages, not this list.");
        sb.AppendLine();
        if (snapshot.Releases.Count == 0)
        {
            sb.AppendLine("No GitHub Releases published.");
            sb.AppendLine();
            return;
        }

        sb.AppendLine("| Published | Repository | Tag | Channel |");
        sb.AppendLine("|-----------|------------|-----|---------|");
        foreach (var row in snapshot.Releases)
        {
            sb.Append("| ").Append(Cell(row.Published));
            sb.Append(" | ").Append(RepoLink(org, row.Repo));
            sb.Append(" | ").Append(Linked($"`{row.Tag}`", row.Url));
            sb.Append(" | ").Append(Cell(row.Channel));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
    }

    private static void AppendInventory(StringBuilder sb, string org, OrgStatusSnapshot snapshot)
    {
        sb.AppendLine("### What we have");
        sb.AppendLine();
        sb.AppendLine("Highest package version on GitHub Packages and on nuget.org, plus the latest release tag.");
        sb.AppendLine();
        sb.AppendLine("| Repository | Packages | GPR | nuget.org | Last release | Merge | Release |");
        sb.AppendLine("|------------|----------|-----|-----------|--------------|-------|---------|");
        foreach (var row in snapshot.Repos)
        {
            var packagesUrl = row.PackageCount > 0
                ? $"[{row.PackageCount}](https://github.com/orgs/{org}/packages?repo_name={row.Name})"
                : "0";
            var release = string.IsNullOrWhiteSpace(row.ReleaseTag)
                ? "—"
                : Linked($"`{row.ReleaseTag}`", row.ReleaseUrl) + (string.IsNullOrWhiteSpace(row.ReleasePublished) ? "" : $" · {Cell(row.ReleasePublished)}");
            sb.Append("| ").Append(RepoLink(org, row.Name));
            sb.Append(" | ").Append(packagesUrl);
            sb.Append(" | ").Append(Mono(row.GprVersion));
            sb.Append(" | ").Append(Mono(row.NugetVersion));
            sb.Append(" | ").Append(release);
            sb.Append(" | ").Append(Linked(Blank(row.MergeConclusion), row.MergeUrl));
            sb.Append(" | ").Append(Linked(Blank(row.ReleaseConclusion), row.ReleaseRunUrl));
            sb.AppendLine(" |");
        }

        sb.AppendLine();
    }

    private static string RepoLink(string org, string repo) =>
        $"[`{repo}`](https://github.com/{org}/{repo})";

    private static string Linked(string label, string url) =>
        string.IsNullOrWhiteSpace(url) ? Cell(label) : $"[{label}]({url})";

    private static string Mono(string version) =>
        string.IsNullOrWhiteSpace(version) ? "—" : $"`{Cell(version)}`";

    private static string Blank(string text) =>
        string.IsNullOrWhiteSpace(text) ? "—" : text;

    private static string Cell(string? text)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return "—";
        }

        return text.Replace("|", "\\|", StringComparison.Ordinal)
            .Replace("\r", " ", StringComparison.Ordinal)
            .Replace("\n", " ", StringComparison.Ordinal)
            .Trim();
    }
}
