<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Novolis.Tools.Manifest</RootNamespace>
    <AssemblyName>Novolis.Tools.Manifest</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
</Project>
