using System.Text;
using System.Text.Encodings.Web;
using System.Text.Json;
using Novolis.Tools.Docs.Site;

namespace Novolis.Tools.Docs.Marketing;

/// <summary>Writes <c>site/repo-catalog.json</c> for the docs portfolio site.</summary>
public static class RepoCatalogExporter
{
    /// <summary>Exports the built-in platform catalog to JSON (with a generated header comment).</summary>
    public static void Export(IReadOnlyDictionary<string, DocsRepoMeta> catalog, string outputPath)
    {
        var ordered = catalog.Keys.OrderBy(static k => k, StringComparer.OrdinalIgnoreCase).ToArray();
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions
        {
            Indented = true,
            Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        }))
        {
            writer.WriteStartObject();
            foreach (var key in ordered)
            {
                var meta = catalog[key];
                writer.WritePropertyName(key);
                writer.WriteStartObject();
                writer.WriteString("tag", meta.Tag);
                writer.WriteString("blurb", meta.Blurb);
                writer.WriteString("desc", meta.Desc);
                writer.WriteStartArray("topics");
                foreach (var topic in meta.Topics)
                {
                    writer.WriteStringValue(topic);
                }

                writer.WriteEndArray();
                writer.WriteEndObject();
            }

            writer.WriteEndObject();
        }

        var jsonBody = Encoding.UTF8.GetString(stream.ToArray()).TrimEnd();
        var header = "// Generated by novolis-docs marketing — do not hand-edit." + Environment.NewLine;
        var dir = Path.GetDirectoryName(outputPath);
        if (!string.IsNullOrEmpty(dir))
        {
            Directory.CreateDirectory(dir);
        }

        File.WriteAllText(outputPath, header + jsonBody + Environment.NewLine, new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));
    }
}
