<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Novolis.Tools.Sqlite.Unit</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="TUnit" />
    <ProjectReference Include="..\..\src\Novolis.Tools.Sqlite\Novolis.Tools.Sqlite.csproj" />
  </ItemGroup>
</Project>
